# Generated by Django 5.0.6 on 2024-06-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=50)),
                ("price", models.IntegerField(default=100)),
                ("desc", models.CharField(max_length=400)),
                ("pub_date", models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name="products",
        ),
    ]
