# Generated by Django 5.0.6 on 2024-06-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0008_orderupdate"),
    ]

    operations = [
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.ImageField(upload_to="prescriptions/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
