# Generated by Django 5.0.6 on 2024-06-23 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Medicine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "identification_number",
                    models.CharField(max_length=255, unique=True),
                ),
                ("expiry_date", models.DateField()),
                ("quantity", models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
